apiVersion: apps/v1
kind: Deployment
metadata:
  name: eshop-billing
  labels:
    app: billing
spec:
  selector:
    matchLabels:
      app: billing
  replicas: 1
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: billing
    spec:
      containers:
        - name: billing
          image: "fedox/liveproject-eshop-billing:1.1.0"
          imagePullPolicy: IfNotPresent
          env:
            - name: JAEGER_ENDPOINT
              value: http://jaeger:14268/api/traces
          ports:
            - name: eshop-billing
              containerPort: 8080
              protocol: TCP
          resources:
            requests:
              memory: 256Mi
              cpu: 100m
            limits:
              memory: 512Mi
              cpu: 200m
          livenessProbe:
            failureThreshold: 3
            successThreshold: 1
            initialDelaySeconds: 60
            periodSeconds: 5
            timeoutSeconds: 40
            httpGet:
              path: /healthcheck
              port: 8080
              scheme: HTTP
          readinessProbe:
            failureThreshold: 3
            initialDelaySeconds: 60
            periodSeconds: 5
            successThreshold: 1
            timeoutSeconds: 40
            httpGet:
              path: /healthcheck
              port: 8080
              scheme: HTTP

---
apiVersion: v1
kind: Service
metadata:
  name: eshop-billing
spec:
  type: ClusterIP
  selector:
    app: billing
  ports:
    - protocol: TCP
      port: 8380
      targetPort: 8080
