server:
  port: 8080

app:
  version: ${PROJECT_VERSION}

tracer:
  trace:
    name: "EShop-Delivery"

services:
  logistic:
    transportEndpoint: ${LOGISTIC_TRANSPORT_ENDPOINT}

logging:
  level:
    com.fedox.study.tracing.delivery: DEBUG