services:
  eshop-checkout:
    image: fedox/liveproject-eshop-checkout:latest
    container_name: eshop-checkout
    environment:
      JAEGER_ENDPOINT: http://jaeger:14268/api/traces
      ORDER_SERVICE_ENDPOINT: http://mockserver:3000/createOrder
      BILLING_PAYMENT_SERVICE_ENDPOINT: http://mockserver:3000/billing/payment
      ARRANGE_DELIVERY_ENDPOINT: http://mockserver:3000/delivery/arrangeDelivery
    ports:
      - 8180:8080
    networks:
      - tracing-checkout-net
    depends_on:
      - jaeger
      - mockserver
  mockserver:
    image: mockoon/cli:5.0.0
    container_name: eshop-services-mocks
    command: ["--data", "data", "--port", "3000"]
    healthcheck:
      test: [ "CMD-SHELL", "curl -f http://localhost:3000/health || exit 1" ]
      interval: 30s
      timeout: 5s
      retries: 2
      start_period: 10s
    volumes:
      - ./mock-configs/eshop-checkout.json:/data:readonly
    networks:
      - tracing-checkout-net

  jaeger:
    image: rancher/jaegertracing-all-in-one:1.20.0
    container_name: jaeger
    ports:
      - 6831:6831/udp
      - 6832:6832/udp
      - 5778:5778
      - 16686:16686
      - 4317:4317
      - 4318:4318
      - 14250:14250
      - 14268:14268
      - 14269:14269
      - 9411:9411
    networks:
      - tracing-checkout-net
    healthcheck:
      test: ["CMD", "curl", "-X", "GET", "localhost:14269"] # jaeger collector health check ping
      interval: 1s
      timeout: 3s
      retries: 60

networks:
  tracing-checkout-net:
    driver: bridge
