services:
  eshop-delivery:
    image: fedox/liveproject-eshop-delivery:latest
    container_name: eshop-delivery
    environment:
      JAEGER_ENDPOINT: http://jaeger:14268/api/traces
      LOGISTIC_TRANSPORT_ENDPOINT: http://eshop-logistics:8080/transport
    ports:
      - 8480:8080
    networks:
      - tracing-delivery-net
    depends_on:
      - jaeger
      - eshop-logistics

  eshop-logistics:
    image: fedox/liveproject-eshop-logistic:latest
    container_name: eshop-logistics
    environment:
      PROJECT_VERSION: 1.0.1-SNAPSHOT
      JAEGER_ENDPOINT: http://jaeger:14268/api/traces
    ports:
      - 8580:8080
    networks:
      - tracing-delivery-net
    depends_on:
      - jaeger

  jaeger:
    image: rancher/jaegertracing-all-in-one:1.20.0
    container_name: jaeger
    ports:
      - 6831:6831/udp
      - 6832:6832/udp
      - 5778:5778
      - 16686:16686
      - 4317:4317
      - 4318:4318
      - 14250:14250
      - 14268:14268
      - 14269:14269
      - 9411:9411
    networks:
      - tracing-delivery-net

networks:
  tracing-delivery-net:
    driver: bridge